name: go_perak
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3

  flutter_gen_runner: ^5.8.0
  build_runner: ^2.4.13
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  flutter_easyloading: ^3.0.5
  lottie: ^3.2.0
  camera: ^0.11.0+2
  http: ^1.3.0
  image_cropper: ^9.0.0
  image_picker: ^1.1.2
  google_ml_kit: ^0.19.0
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  pin_code_fields: ^8.0.1
  carousel_slider: ^5.0.0
  json_serializable: ^6.9.4
  json_annotation: ^4.9.0
  
  #firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  
  fluttertoast: ^8.2.12
  flutter_rating_bar: ^4.0.1
  supabase_flutter: ^2.8.4
  intl: ^0.20.2
  multi_select_flutter: ^4.1.3
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  google_maps_flutter: ^2.12.1
  geolocator: ^14.0.0
  url_launcher: ^6.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_gen:
  output: lib/generated/
  integrations:
    image: true
    flutter_svg: true
    rive: true
    lottie: true
  

  assets:
    # style: dot-delimiter
    outputs: 
      package_parameter_enabled: true
      directory_path_enabled: true

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/animations/
  - assets/jsons/
