name: go_perak
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3

  flutter_gen_runner: ^5.8.0
  build_runner: ^2.4.13
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_gen:
  output: lib/generated/

  assets:
    style: dot-delimiter

flutter:
  uses-material-design: true
  assets:
  - assets/images/
