// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1iky4SEc4dxJBuHw91eX4DEVZPPRZ9Jc',
    appId: '1:572338477821:web:058a617108c7c5ec053c94',
    messagingSenderId: '572338477821',
    projectId: 'goperak-60731',
    authDomain: 'goperak-60731.firebaseapp.com',
    storageBucket: 'goperak-60731.firebasestorage.app',
    measurementId: 'G-VQZDDJ2B9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3DGgAXuViBjyOo2UzwG36JrBWrRUbB7U',
    appId: '1:572338477821:android:f22eeabc6539f6f0053c94',
    messagingSenderId: '572338477821',
    projectId: 'goperak-60731',
    storageBucket: 'goperak-60731.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS69HkEEWDXA_1Uhj59RCme1TWSG_iKWU',
    appId: '1:572338477821:ios:8e123819e1b47df5053c94',
    messagingSenderId: '572338477821',
    projectId: 'goperak-60731',
    storageBucket: 'goperak-60731.firebasestorage.app',
    iosBundleId: 'com.example.goPerak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS69HkEEWDXA_1Uhj59RCme1TWSG_iKWU',
    appId: '1:572338477821:ios:8e123819e1b47df5053c94',
    messagingSenderId: '572338477821',
    projectId: 'goperak-60731',
    storageBucket: 'goperak-60731.firebasestorage.app',
    iosBundleId: 'com.example.goPerak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1iky4SEc4dxJBuHw91eX4DEVZPPRZ9Jc',
    appId: '1:572338477821:web:3382617765167308053c94',
    messagingSenderId: '572338477821',
    projectId: 'goperak-60731',
    authDomain: 'goperak-60731.firebaseapp.com',
    storageBucket: 'goperak-60731.firebasestorage.app',
    measurementId: 'G-V5P6FB2SVJ',
  );
}
